caFilePath: /opt/homebrew/etc/ca-certificates/cert.pem

npmRegistryServer: "https://artifactory.global.square/artifactory/api/npm/square-npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
